### PR TITLE
Option to prefer or avoid brave chains (Experimental)

### PR DESCRIPTION
**Pull request by MathewSachin**
I'm thinking of keeping the `Experimental` label since these features don't work in all cases.

A `Brave Chains` setting added in `More options` with the following possible values:
- Don't care
- After NP (Doesn't care about the Cards before NP)
   Attempt towards resolving #137 
  Tracks the first NP used from AutoSkill and gives priority to the same servant's face cards.
  Uses as many cards of the same servant is available while respecting Card Priority settings after which it falls back to the normal Card Priority handling.
  Doesn't work with NP Spam/Danger
- Avoid
   Avoids brave chains if possible. Useful if you're face-card farming (e.g. bones) or want to finish up remaining health of 2 enemies after NPs.

### Rearranging cards (Configurable)
When clicking 3 cards, move the card with 2nd highest priority to last position to amplify its effect
 (A,B,C -> A,C,B) when A > B > C
Do the same when clicking 2 cards unless they're used before NPs.

Skip if:
- NP spamming because we don't know how many NPs might've been used.
- in Avoid brave chain mode because it tries to get consecutive cards to be not of the same servant.

### CODE REVIEW

**Comment by reconman** [comment]
Why would you avoid brave chains?

**Comment by reconman** [comment]
> Detects if NPs are loaded using Edge detection: This part needs tweaking. Danger mode doesn't seem to work even outside this PR?

When I last tested this 2-3 months ago, it was still working.

**Comment by MathewSachin** [comment]
> When I last tested this 2-3 months ago, it was still working.

Yeah, used to work earlier. I only tested in the summer nodes where it didn't work for me.

**Comment by MathewSachin** [comment]
Oh, does Danger mode only work if Auto-targeting is ON? Seems so from the code.

**Comment by MathewSachin** [comment]
I'm merging this PR now since it is getting difficult to test multiple features with the restriction on AP.
Shouldn't be much of a problem since both of the features in this PR are marked as Experimental and are opt-in.

**Comment by reconman** [comment]
Sorry, I was quite busy the past few days.

**Comment by MathewSachin** [comment]
Yeah, I understand. I wanted to test this with #231. That seems to be working pretty good on NA. JP doesn't have an event right now, so wasn't able to get an image of `Unable to find support matching criteria` screen yet.

**Pull request merged**
