### PR TITLE
Wait for AP Regeneration

### PR DESCRIPTION
**Pull request by the3dsandwich**
Following #609 and after fixing branch/forking problems on my side as mentioned in #610 

I rebased my branch with the main branch then rewrote the function. I want to test it for a night before saying this works reliably, but I hope it is ok that I put the new PR here first.

### CODE REVIEW

**Comment by MathewSachin** [comment]
The code does look absolutely fine 👍 
But, yeah, it's always a good idea to test more.

**Comment by the3dsandwich** [comment]
I'll let you know tomorrow if the update worked as planned!

**Comment by the3dsandwich** [comment]
So after testing for a night, this commit works the way I wanted it to be. If you like it then it's ok for merging. Thanks!

**Comment by MathewSachin** [comment]
Looks good! merging, thanks 👍

**Pull request merged**
