### PR TITLE
Support edits in AutoSkillMaker

### LINKED ISSUE #271: Ability to edit certain parts/ wave of skill command
For fixing mistakes

### PR DESCRIPTION
**Pull request by MathewSachin**
Finally, after pretty much rewriting the AutoSkillMaker, we can support editing the skill command.
fixes #271

But, I'm not sure if the text box to enter Skill commands should be removed entirely.

### CODE REVIEW

**Comment by potchy** [comment]
> But, I'm not sure if the text box to enter Skill commands should be removed entirely.

pls no

**Comment by MathewSachin** [comment]
@potchy Sure, I can't say no to you

**Comment by MathewSachin** [comment]
> Made AutoSkillMaker the default and added an option to show TextBox

@potchy I think this should keep everyone happy

**Comment by AlfredPaguio** [comment]
Thanks

**Comment by sleeping-player** [comment]
#336
I think I'm now speaking out of bounds, but there might be an easier way.

autoskill maker GUI editor->lua format

When this app handles scripts in GUI state, it has not yet converted to lua format, and individual commands can be separated. Wouldn't it be possible to save intermediate data in new file format as it was in memory?  This format could be edited, run directly from the app, or converted to lua format.

**Comment by MathewSachin** [comment]
@sleeping-player I think I didn't get your comment. The issue linked was for translation, but what you wrote seems to be about AutoSkillMaker?

By Lua format, I assume you mean the AutoSkill command.
I did rewrite AutoSkillMaker to use an intermediate format that can convert to and from lua format.
Even the AutoSkill module uses that format now. But, we can't get rid of the Lua format or everyone's existing skill commands would break.

**Comment by sleeping-player** [comment]
Oh I'm sorry. I'm worried and misunderstood that you're struggling with a way to push editing features while keeping the existing format.
I mentioned that issue as your last comment expressed very difficulty with the autoskill job.
If it's going well, just thank you.

**Comment by MathewSachin** [comment]
The AutoSkill editor work is already done.
That was indeed difficult. I had to rewrite parts of how the AutoSkill module work and pretty much rewrite AutoSkill Maker.
This PR is only the final part of that. If you check the commit history for the past few weeks, you could see what all was done to reach the final goal of making AutoSkill Maker support editing.
I just finished that and that was a lot of work.
I mentioned that I don't want to immediately start another big task.

**Comment by MathewSachin** [comment]
Here you go. All the commits that finally led to editing support in AutoSkillMaker.

- https://github.com/MathewSachin/Fate-Grand-Automata/commit/5861f26262f349b85b34c6e1cb642f512bd40c8c
- https://github.com/MathewSachin/Fate-Grand-Automata/commit/07918671db68aa9543b5dd879f4d96328b8d7bea
- https://github.com/MathewSachin/Fate-Grand-Automata/commit/733171fc940cc23f94495933475908f3b59dc7e2
- https://github.com/MathewSachin/Fate-Grand-Automata/commit/fa35004d9a72a52ff5e16eb917d4ec46d9abe22c
- https://github.com/MathewSachin/Fate-Grand-Automata/commit/cb2af7a847f627c1e58156f153b7cc2aa8be503c
- https://github.com/MathewSachin/Fate-Grand-Automata/commit/1a1c63d25ca670083fb8ad41b41e1151e11a5bea
- https://github.com/MathewSachin/Fate-Grand-Automata/commit/09fed3d2689252f5f6881a2c55cdb354ee7c8046
- https://github.com/MathewSachin/Fate-Grand-Automata/commit/d85118a99b828d0c872299e509ee1793737ae32c
- https://github.com/MathewSachin/Fate-Grand-Automata/commit/d7001188fff1ead44ebe831f604b359e37d2f195
- https://github.com/MathewSachin/Fate-Grand-Automata/commit/42b88e1be7ed2dd123c603c14dd65abbe27341af

**Pull request merged**
