### PR TITLE
Repeat Screen and FP summon update for KR

### LINKED ISSUE #382: Upcoming KR Update
When : https://cafe.naver.com/fategokr/2259707
Sep 15th 10:30~15:00 GMT+9
(correction: this type maintenance are usually delayed)
What : https://cafe.naver.com/fategokr/2252992
very much pictures

Oh I forgot to check issue type...

### PR DESCRIPTION
**Pull request by MathewSachin**
fixes #382

### CODE REVIEW

**Comment by MathewSachin** [comment]
@sleeping-player @ScathachSkadi can you try the build from this PR?

**Comment by ScathachSkadi** [comment]
Right on it

**Comment by sleeping-player** [comment]
CI build waited

**Comment by ScathachSkadi** [comment]
FP gacha works fine. And the repeat quest button is getting tapping correctly.

**Comment by sleeping-player** [comment]
repeating works fine, and FP gacha also works fine.
and from now on I must turn off ignore notch calculation option.

**Pull request merged**
