### PR TITLE
Add Support Swipe Multiplier to Gift Box

### PR DESCRIPTION
**Pull request by the3dsandwich**
Solves #457 

For now I think copying and modifying `scrollList()` from `Support.kt` is enough, though you may be interested in making swiping in a separate module so other scripts can refer to it?

Let me prepare a working screen recording before this can be merged.

### CODE REVIEW

**Comment by the3dsandwich** [comment]
[Screen Recording](https://youtu.be/o6aJbJHgxy0)

**Comment by MathewSachin** [comment]
#430 is one more case where we would potentially need to swipe, so I was thinking of renaming `supportSwipeMultiplier` to `swipeMultiplier` and putting the linear interpolation code into the `swipe` function.

But, for that, the `swipeMultiplier` should go into [IPlatformPrefs](https://github.com/MathewSachin/Fate-Grand-Automata/blob/master/libautomata/src/main/java/com/mathewsachin/libautomata/IPlatformPrefs.kt)

Also, the interpolation is only done along Y-axis right now. We need to do it along X-axis too for it to be generalized.

**Comment by the3dsandwich** [comment]
Yeah I think that is a better way to implement swipes. But if you need a quick and dirty way to get gift box working before the generalized solution then I guess here's this.

**Comment by reconman** [comment]
I fully support what Mathew proposed. I will use your version for now, but I'd rather not put something into the master branch temporarily.

**Comment by MathewSachin** [comment]
No problem. I'll take this up.
@the3dsandwich would this be the right translation for `Swipe multiplier`: `滑動乘`?
In Korean, the words were separate, so I could make sense, but not sure about TW.

**Comment by the3dsandwich** [comment]
Let me think about the translation. The wording of 滑動乘 doesn't sound natural enough.  I'm thinking along the lines of 滑動微調 (slide tweak/fine-tuning) or 滑動加乘 (slide multiplication). Let me sit on both names for a day or so and see which one sticks

**Comment by MathewSachin** [comment]
Closing in favour of #464 

Swipe multiplier would apply to all swipes

I rewrote how scrolling works on Android 8 and above, so we might not need to set Swipe multiplier at all for them.

**Pull request closed without merging**
